#!/bin/bash

# dump docker container run variable into a file for systemd to load
env > /container.env.vars

# Wait for postgres to be up
echo "== Checking ${DATABASE_SERVICE_NAME}:5432 status =="

while true; do
  /usr/bin/ncat ${DATABASE_SERVICE_NAME} 5432 < /dev/null && break                                
  sleep 5                                                                             
done                                                                                  
echo "${DATABASE_SERVICE_NAME}:5432 - accepting connections"                                

exec "$@"
